stages: -test -build

code_quality:
    image: node:20.12.1
    stage: test
    before_script: -npm ci
    script:
        - npm run eslint
        - npm run stylelint
        - npm run prettier-check
    only: marge_requests

    build:
        image: node:20.12.1
        stage: build
        before_script: -npm ci
        script:
            - npm run build
        only: marge_requests
